name: alist
services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "./config/caddy/Caddyfile:/etc/caddy/Caddyfile"
      - "./config/caddy/config:/config"
      - "./config/caddy/data:/data"
    restart: always
    depends_on:
      alist:
        condition: service_healthy
      s-ui:
        condition: service_started

  alist:
    image: xhofe/alist:latest
    container_name: alist
#   Remove the port mapping to the host and access it through Caddy’s internal network
#   ports:
#     - 5244:5244
    volumes:
      - "./config/alist:/opt/alist/data"
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5244 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 40
    restart: unless-stopped

  s-ui:
    image: alireza7/s-ui:v1.3.7
    container_name: s-ui
    network_mode: host  # key configuration
    volumes:
      - "./config/s-ui/db:/app/db"
      - "./config/s-ui/cert:/app/cert"
      # Share Caddy’s certificates directory with s-ui container as read-only, for example:
      # /app/ssl/us.pm6422.site/us.pm6422.site.key
      # /app/ssl/us.pm6422.site/us.pm6422.site.crt
#      - "./config/caddy/data/caddy/certificates/acme-v02.api.letsencrypt.org-directory:/app/ssl:ro"
    environment:
      - TZ=Asia/Shanghai
    entrypoint: ./entrypoint.sh
    hostname: s-ui
    restart: unless-stopped