name: alist
services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./config/caddy/data:/data
      - ./config/caddy/config:/config
    restart: always
    depends_on:
      alist:
        condition: service_healthy
  alist:
    image: alist666/alist:latest
    container_name: alist
#   移除端口映射到宿主机，通过Caddy内部网络访问
#    ports:
#      - 5244:5244
    volumes:
      - ./config/alist:/opt/alist/data
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:5244" ]
      interval: 5s
      timeout: 5s
      retries: 40
    restart: unless-stopped

