name: alist
services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./config/caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./config/caddy/data:/data
      - ./config/caddy/config:/config
    healthcheck:
      test: ["CMD", "caddy", "health"]
      interval: 5s
      timeout: 5s
      retries: 40
    restart: always
    depends_on:
      alist:
        condition: service_healthy
  alist:
    image: xhofe/alist:latest
    container_name: alist
#   Remove the port mapping to the host and access it through Caddyâ€™s internal network
#    ports:
#      - 5244:5244
    volumes:
      - ./config/alist:/opt/alist/data
    environment:
      - PUID=0
      - PGID=0
      - UMASK=022
      - TZ=Asia/Shanghai
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:5244 || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 40
    restart: unless-stopped

